### ISSUE TITLE
Feature: remove notify for remotes if server is localhost

### ISSUE THREAD

**Issue by mave007** [icann-dns/puppet-nsd#17]
If we define into the YAML the following:

```yaml
dns::daemon: nsd
dns::remotes:
  localhost:
    address4: 127.0.0.1
    address6: '0::1'
    tsig_name: 'NOKEY'
```

The output for `nsd.conf` will be:

```bash
pattern:
  name: localhost-master
  allow-notify: 127.0.0.1 NOKEY
  request-xfr: AXFR 127.0.0.1 NOKEY
  allow-notify: 0::1 NOKEY
  request-xfr: AXFR 0::1 NOKEY
```

It would be useful to have somehow `allow-notify` parameter on NSD to be empty if it is localhost.
