### ISSUE TITLE
Seperate options for provide_xfr and notify

### ISSUE THREAD

**Issue by htj** [icann-dns/puppet-nsd#18]
Hi

I have a case where I need to provide XFR to two IPs, but only notify one of them.

It has to do with an multi homed host with an anycast address. This config is perfectly in the nsd.conf file, but not currently possible with the puppet-nsd module, as the list of provide_xfrs is also used for the notify list.

**Comment by b4ldr** [comment]
@htj Im curious if this actually causes an issue in your config?  Anyway that aside you can abuse the fact that [if you provide a prefix as the remote then the notify is not configured](https://github.com/icann-dns/puppet-nsd/blob/master/templates/etc/nsd/nsd.patterns.conf.erb#L18-L20) e.g.

```yaml
nsd::remotes:
  slave_notify: 192.0.2.1
  slave_no_notify: 192.0.2.2/32
  slave_no_notify_ipv6: 2001:db8::1/128
nsd::default_provide_xfrs:
  - slave_notify
  - slave_no_notify
  - slave_no_notify_ipv6
nsd::zones:
  example.org: {}
```
